# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Sphinx build configuration for edi-bots-server

version: 2

sphinx:
  builder: html
  configuration: docs/conf.py

python:
  version: 3
  install:
    - requirements: docs/requirements.txt
